[WIP] Implement server
ubuntuegor/bebroo pull request #1
Opened 2021-11-28 15:23 UTC by ubuntuegor

2021-11-28 17:33 UTC, samorojy commented
I am **fascinated** by this code! 😋

2021-12-06 08:59 UTC, nbirillo requested changes

2021-12-06 08:59 UTC, nbirillo commented on server/api.md
> +`GET /api/users/me` — get info about current user
Как правило не делают me в пути для того, чтобы достать что-то текущему юзеру. Лучше делать один путь - например, `/api/user/profile` или что угодно (часто кстати единственное число именно используют) и дальше смотреть, если пользователь авторизован, то отдавать его профиль, если нет, кидать ошибку, что не авторизован например. А дальше если надо будет ходить по профилям юзеров, то приписывают айдишник (публичный) или там юзернейм, короче что-то, что уникально, через параметры, например `/api/user/profile?id=2` и тд

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/Api.kt
> +fun Application.api(testing: Boolean = false) {
Boolean переменные лучше называть с is\has и тд

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/Api.kt
> +                val userExists = transaction {
isExist?

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/Api.kt
> +        jwt("user") {
Не хотите по функциям раскидать jwt, oauth и тд? а то при добавлении еще способа авторизации это все еще вырастет... и будет совсем сложно читать

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/Api.kt
> +                    name = "google",
Я бы предложила сделать еще какой-нибудь object или что-то, где вы будете хранить эти все переменные для авторизацйи (то же и для jwt)

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/GoogleOAuth.kt
> +            if (principal == null) {
а как же наш любимый элвис оператор и let?

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/GoogleOAuth.kt
> +                        mapOf("errorText" to "Не удалось выполнить вход")
Всякие константы лучше выносить в константы

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/GoogleOAuth.kt
> +                    if (user != null) {
перепишите на котлиновский стиль, ребят ;)

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/GoogleOAuth.kt
> +fun Route.googleOAuth() {
А еще очень большая функция и ее здорово разбить на несколько

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/UserData.kt
> +            val userId = call.principal<JWTPrincipal>()?.payload?.getClaim("id")?.asInt()!!
Может обработаете тут с помощью ?: ?

2021-12-06 08:59 UTC, nbirillo commented on server/src/main/kotlin/to/bnt/draw/server/api/users/UserData.kt
> +            val userId = call.principal<JWTPrincipal>()?.payload?.getClaim("id")?.asInt()!!
и тут

2021-12-12 19:29 UTC, closed without merging